2020/01/02 03:52:50 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii". in C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp2020\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp2020\htdocs\multiuser\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/multiuser/index.php?r=gii
---
2020/01/02 04:48:23 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "user". in C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp2020\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp2020\htdocs\multiuser\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/multiuser/index.php?r=user
---
2020/01/02 04:48:53 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "user". in C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp2020\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp2020\htdocs\multiuser\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/multiuser/index.php?r=user
---
2020/01/02 04:49:22 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "user". in C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp2020\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp2020\htdocs\multiuser\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/multiuser/index.php?r=user
---
2020/01/03 02:51:43 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp2020\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp2020\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp2020\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp2020\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp2020\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp2020\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp2020\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp2020\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp2020\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp2020\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp2020\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp2020\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp2020\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp2020\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp2020\htdocs\multiuser\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/multiuser/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/multiuser/index.php?r=gii/default/index
---
2020/01/03 02:51:58 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp2020\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp2020\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp2020\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp2020\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp2020\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp2020\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp2020\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp2020\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp2020\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp2020\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp2020\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp2020\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp2020\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp2020\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp2020\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp2020\htdocs\multiuser\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/multiuser/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/multiuser/index.php?r=gii/default/index
---
2020/01/04 19:15:12 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp2\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tbOffice/index....')
#3 C:\xampp2\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp2\htdocs\multiuser\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/multiuser/index.php?r=tbOffice/index.php
---
2020/01/04 19:22:32 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index.php?r=tbOffice". in C:\xampp2\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index.php?r=tbO...')
#1 C:\xampp2\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp2\htdocs\multiuser\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/multiuser/index.php?r=index.php?r=tbOffice
HTTP_REFERER=http://localhost/multiuser/index.php?r=tbOffice
---
2020/01/04 19:23:39 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "tbOffice". in C:\xampp2\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('tbOffice')
#1 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('tbOffice')
#2 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/tbOffice')
#3 C:\xampp2\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp2\htdocs\multiuser\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/multiuser/index.php?r=site/tbOffice
HTTP_REFERER=http://localhost/multiuser/index.php?r=site/index
---
2020/01/04 19:24:50 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "?r=tbOffice". in C:\xampp2\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('?r=tbOffice')
#1 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('?r=tbOffice')
#2 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tbOffice/?r=tbO...')
#3 C:\xampp2\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp2\htdocs\multiuser\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/multiuser/index.php?r=tbOffice/?r=tbOffice
HTTP_REFERER=http://localhost/multiuser/index.php?r=tbOffice
---
2020/01/04 19:25:47 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "?r=tbOffice". in C:\xampp2\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('?r=tbOffice')
#1 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('?r=tbOffice')
#2 C:\xampp2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/?r=tbOffic...')
#3 C:\xampp2\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp2\htdocs\multiuser\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/multiuser/index.php?r=site/?r=tbOffice
HTTP_REFERER=http://localhost/multiuser/index.php?r=site/index
---
